[versions]
kotlin = "1.9.22"
mavenPublish = "0.29.0"

[libraries]
aws = { module = "software.amazon.awssdk:s3", version = "2.23.8" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "4.12.0" }
gson = { module = "com.google.code.gson:gson", version = "2.10.1" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish.base", version.ref = "mavenPublish" }

